

### post
POST http://localhost:3000/api/jfy/post
content-type: application/json

{
  "name": "ASUS FHD Gaming Laptop",
  "price": "$960",
  "image": "/bell-try-to-test-image/wired-keyboard.png"
}

### get
GET http://localhost:3000/api/jfy/1


### find all
GET http://localhost:3000/api/jfy/

### Delete 
Delete http://localhost:3000/api/jfy/delete/

### Delete all
Delete http://localhost:3000/api/jfy/delete-all